<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260502202915 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create Billing module tables (suppliers, invoices, invoice lines, OCR jobs)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE billing_invoice_lines (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(500) NOT NULL, quantity NUMERIC(12, 4) DEFAULT \'1.0000\' NOT NULL, unit_price_cents INT DEFAULT NULL, vat_rate_bp INT DEFAULT NULL, total_net_cents INT DEFAULT NULL, position INT DEFAULT 0 NOT NULL, invoice_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BFB98DFB2989F1FD ON billing_invoice_lines (invoice_id)');
        $this->addSql('CREATE TABLE billing_invoices (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number VARCHAR(64) DEFAULT NULL, status VARCHAR(16) DEFAULT \'draft\' NOT NULL, issued_at DATE DEFAULT NULL, due_at DATE DEFAULT NULL, paid_at DATE DEFAULT NULL, currency VARCHAR(3) DEFAULT \'EUR\' NOT NULL, total_net_cents INT DEFAULT NULL, total_vat_cents INT DEFAULT NULL, total_gross_cents INT DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, supplier_id INT DEFAULT NULL, document_id INT DEFAULT NULL, ocr_job_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_72F346692ADD6D8C ON billing_invoices (supplier_id)');
        $this->addSql('CREATE INDEX IDX_72F34669C33F7837 ON billing_invoices (document_id)');
        $this->addSql('CREATE INDEX IDX_72F3466927426A53 ON billing_invoices (ocr_job_id)');
        $this->addSql('CREATE INDEX idx_billing_invoice_status ON billing_invoices (status)');
        $this->addSql('CREATE INDEX idx_billing_invoice_issued_at ON billing_invoices (issued_at)');
        $this->addSql('CREATE TABLE billing_ocr_jobs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(32) DEFAULT \'queued\' NOT NULL, model_used VARCHAR(100) DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, raw_doctr JSON DEFAULT NULL, raw_vlm JSON DEFAULT NULL, extracted JSON DEFAULT NULL, confidence DOUBLE PRECISION DEFAULT NULL, error TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, media_id INT NOT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BB1514F3EA9FDD75 ON billing_ocr_jobs (media_id)');
        $this->addSql('CREATE INDEX IDX_BB1514F3B03A8386 ON billing_ocr_jobs (created_by_id)');
        $this->addSql('CREATE INDEX idx_billing_ocr_status ON billing_ocr_jobs (status)');
        $this->addSql('CREATE TABLE billing_suppliers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, vat_number VARCHAR(64) DEFAULT NULL, registration_number VARCHAR(64) DEFAULT NULL, iban VARCHAR(34) DEFAULT NULL, bic VARCHAR(11) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, address TEXT DEFAULT NULL, country_code VARCHAR(2) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, company_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_183BDB02979B1AD6 ON billing_suppliers (company_id)');
        $this->addSql('ALTER TABLE billing_invoice_lines ADD CONSTRAINT FK_BFB98DFB2989F1FD FOREIGN KEY (invoice_id) REFERENCES billing_invoices (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE billing_invoices ADD CONSTRAINT FK_72F346692ADD6D8C FOREIGN KEY (supplier_id) REFERENCES billing_suppliers (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE billing_invoices ADD CONSTRAINT FK_72F34669C33F7837 FOREIGN KEY (document_id) REFERENCES media (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE billing_invoices ADD CONSTRAINT FK_72F3466927426A53 FOREIGN KEY (ocr_job_id) REFERENCES billing_ocr_jobs (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE billing_ocr_jobs ADD CONSTRAINT FK_BB1514F3EA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE billing_ocr_jobs ADD CONSTRAINT FK_BB1514F3B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE billing_suppliers ADD CONSTRAINT FK_183BDB02979B1AD6 FOREIGN KEY (company_id) REFERENCES crm_companies (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE billing_invoice_lines DROP CONSTRAINT FK_BFB98DFB2989F1FD');
        $this->addSql('ALTER TABLE billing_invoices DROP CONSTRAINT FK_72F346692ADD6D8C');
        $this->addSql('ALTER TABLE billing_invoices DROP CONSTRAINT FK_72F34669C33F7837');
        $this->addSql('ALTER TABLE billing_invoices DROP CONSTRAINT FK_72F3466927426A53');
        $this->addSql('ALTER TABLE billing_ocr_jobs DROP CONSTRAINT FK_BB1514F3EA9FDD75');
        $this->addSql('ALTER TABLE billing_ocr_jobs DROP CONSTRAINT FK_BB1514F3B03A8386');
        $this->addSql('ALTER TABLE billing_suppliers DROP CONSTRAINT FK_183BDB02979B1AD6');
        $this->addSql('DROP TABLE billing_invoice_lines');
        $this->addSql('DROP TABLE billing_invoices');
        $this->addSql('DROP TABLE billing_ocr_jobs');
        $this->addSql('DROP TABLE billing_suppliers');
    }
}
