<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260424183257 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add post_revisions table to store per-post edit history snapshots';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE post_revisions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, post_version INT NOT NULL, status VARCHAR(50) NOT NULL, snapshot JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, post_id INT NOT NULL, author_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_28DF5C724B89032C ON post_revisions (post_id)');
        $this->addSql('CREATE INDEX IDX_28DF5C72F675F31B ON post_revisions (author_id)');
        $this->addSql('CREATE INDEX IDX_post_revision_post_created ON post_revisions (post_id, created_at)');
        $this->addSql('ALTER TABLE post_revisions ADD CONSTRAINT FK_28DF5C724B89032C FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post_revisions ADD CONSTRAINT FK_28DF5C72F675F31B FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE post_revisions DROP CONSTRAINT FK_28DF5C724B89032C');
        $this->addSql('ALTER TABLE post_revisions DROP CONSTRAINT FK_28DF5C72F675F31B');
        $this->addSql('DROP TABLE post_revisions');
    }
}
