<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260418072331 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE locales (code VARCHAR(10) NOT NULL, name VARCHAR(100) NOT NULL, is_default BOOLEAN NOT NULL, is_active BOOLEAN NOT NULL, position INT NOT NULL, PRIMARY KEY (code))');
        $this->addSql('CREATE TABLE media (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filename VARCHAR(255) NOT NULL, original_name VARCHAR(255) NOT NULL, mime_type VARCHAR(100) NOT NULL, size INT NOT NULL, path VARCHAR(255) NOT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, alt VARCHAR(255) DEFAULT NULL, caption TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE menu_items (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(10) NOT NULL, label VARCHAR(255) NOT NULL, url VARCHAR(500) NOT NULL, open_in_new_tab BOOLEAN NOT NULL, position INT NOT NULL, parent_id INT DEFAULT NULL, menu_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_70B2CA2A727ACA70 ON menu_items (parent_id)');
        $this->addSql('CREATE INDEX IDX_70B2CA2ACCD7E912 ON menu_items (menu_id)');
        $this->addSql('CREATE TABLE menus (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, location VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_727508CF5E9E89CB ON menus (location)');
        $this->addSql('CREATE TABLE post_translations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(10) NOT NULL, title VARCHAR(255) DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, blocks JSON NOT NULL, meta_title VARCHAR(255) DEFAULT NULL, meta_description TEXT DEFAULT NULL, custom_fields JSON NOT NULL, post_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6D8AA7544B89032C ON post_translations (post_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6D8AA7544B89032C4180C698 ON post_translations (post_id, locale)');
        $this->addSql('CREATE TABLE post_type_fields (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, label VARCHAR(100) NOT NULL, type VARCHAR(50) NOT NULL, required BOOLEAN NOT NULL, translatable BOOLEAN NOT NULL, options JSON NOT NULL, position INT NOT NULL, post_type_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B172029FF8A43BA0 ON post_type_fields (post_type_id)');
        $this->addSql('CREATE TABLE post_types (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(100) NOT NULL, label VARCHAR(100) NOT NULL, icon VARCHAR(50) DEFAULT NULL, has_archive BOOLEAN NOT NULL, is_built_in BOOLEAN NOT NULL, supports JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CE2B05DF989D9B62 ON post_types (slug)');
        $this->addSql('CREATE TABLE posts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, post_type_id INT NOT NULL, featured_media_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_885DBAFAF8A43BA0 ON posts (post_type_id)');
        $this->addSql('CREATE INDEX IDX_885DBAFAE2532148 ON posts (featured_media_id)');
        $this->addSql('CREATE TABLE settings (key VARCHAR(100) NOT NULL, value TEXT DEFAULT NULL, type VARCHAR(50) NOT NULL, "group" VARCHAR(100) DEFAULT NULL, PRIMARY KEY (key))');
        $this->addSql('CREATE TABLE themes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(100) NOT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, active BOOLEAN NOT NULL, config JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_154232DE989D9B62 ON themes (slug)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, name VARCHAR(100) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('ALTER TABLE menu_items ADD CONSTRAINT FK_70B2CA2A727ACA70 FOREIGN KEY (parent_id) REFERENCES menu_items (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE menu_items ADD CONSTRAINT FK_70B2CA2ACCD7E912 FOREIGN KEY (menu_id) REFERENCES menus (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post_translations ADD CONSTRAINT FK_6D8AA7544B89032C FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post_type_fields ADD CONSTRAINT FK_B172029FF8A43BA0 FOREIGN KEY (post_type_id) REFERENCES post_types (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE posts ADD CONSTRAINT FK_885DBAFAF8A43BA0 FOREIGN KEY (post_type_id) REFERENCES post_types (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE posts ADD CONSTRAINT FK_885DBAFAE2532148 FOREIGN KEY (featured_media_id) REFERENCES media (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE menu_items DROP CONSTRAINT FK_70B2CA2A727ACA70');
        $this->addSql('ALTER TABLE menu_items DROP CONSTRAINT FK_70B2CA2ACCD7E912');
        $this->addSql('ALTER TABLE post_translations DROP CONSTRAINT FK_6D8AA7544B89032C');
        $this->addSql('ALTER TABLE post_type_fields DROP CONSTRAINT FK_B172029FF8A43BA0');
        $this->addSql('ALTER TABLE posts DROP CONSTRAINT FK_885DBAFAF8A43BA0');
        $this->addSql('ALTER TABLE posts DROP CONSTRAINT FK_885DBAFAE2532148');
        $this->addSql('DROP TABLE locales');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE menu_items');
        $this->addSql('DROP TABLE menus');
        $this->addSql('DROP TABLE post_translations');
        $this->addSql('DROP TABLE post_type_fields');
        $this->addSql('DROP TABLE post_types');
        $this->addSql('DROP TABLE posts');
        $this->addSql('DROP TABLE settings');
        $this->addSql('DROP TABLE themes');
        $this->addSql('DROP TABLE users');
    }
}
