<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260426152705 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create ecommerce_listings table (Ecommerce module — Listing entity).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE ecommerce_listings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(200) NOT NULL, marketing_title VARCHAR(200) DEFAULT NULL, marketing_description TEXT DEFAULT NULL, is_visible_on_shop BOOLEAN DEFAULT true NOT NULL, seo_title VARCHAR(200) DEFAULT NULL, seo_description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, product_id INT NOT NULL, featured_image_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_10E893B4584665A ON ecommerce_listings (product_id)');
        $this->addSql('CREATE INDEX IDX_10E893B3569D950 ON ecommerce_listings (featured_image_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_ecommerce_listing_slug ON ecommerce_listings (slug)');
        $this->addSql('ALTER TABLE ecommerce_listings ADD CONSTRAINT FK_10E893B4584665A FOREIGN KEY (product_id) REFERENCES erp_products (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ecommerce_listings ADD CONSTRAINT FK_10E893B3569D950 FOREIGN KEY (featured_image_id) REFERENCES media (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE ecommerce_listings DROP CONSTRAINT FK_10E893B4584665A');
        $this->addSql('ALTER TABLE ecommerce_listings DROP CONSTRAINT FK_10E893B3569D950');
        $this->addSql('DROP TABLE ecommerce_listings');
    }
}
