<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260429203634 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE photo_galleries (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(80) NOT NULL, title VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, password_hash VARCHAR(255) DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, allow_originals BOOLEAN DEFAULT true NOT NULL, allow_zip_download BOOLEAN DEFAULT true NOT NULL, picks_require_identity BOOLEAN DEFAULT false NOT NULL, finalized_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, finalized_by_name VARCHAR(200) DEFAULT NULL, finalized_by_email VARCHAR(180) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cover_media_id INT DEFAULT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FAF03896989D9B62 ON photo_galleries (slug)');
        $this->addSql('CREATE INDEX IDX_FAF03896329A1B2E ON photo_galleries (cover_media_id)');
        $this->addSql('CREATE INDEX IDX_FAF03896B03A8386 ON photo_galleries (created_by_id)');
        $this->addSql('CREATE TABLE photo_gallery_items (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position INT DEFAULT 0 NOT NULL, caption TEXT DEFAULT NULL, gallery_id INT NOT NULL, media_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_81B213B94E7AF8F ON photo_gallery_items (gallery_id)');
        $this->addSql('CREATE INDEX IDX_81B213B9EA9FDD75 ON photo_gallery_items (media_id)');
        $this->addSql('CREATE INDEX idx_gallery_position ON photo_gallery_items (gallery_id, position)');
        $this->addSql('CREATE UNIQUE INDEX uniq_gallery_media ON photo_gallery_items (gallery_id, media_id)');
        $this->addSql('CREATE TABLE photo_gallery_picks (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, visitor_token VARCHAR(64) NOT NULL, visitor_name VARCHAR(200) DEFAULT NULL, visitor_email VARCHAR(180) DEFAULT NULL, picked_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, gallery_item_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1CE6B23C2A151376 ON photo_gallery_picks (gallery_item_id)');
        $this->addSql('CREATE INDEX idx_pick_token ON photo_gallery_picks (visitor_token)');
        $this->addSql('CREATE UNIQUE INDEX uniq_pick_per_visitor ON photo_gallery_picks (gallery_item_id, visitor_token)');
        $this->addSql('ALTER TABLE photo_galleries ADD CONSTRAINT FK_FAF03896329A1B2E FOREIGN KEY (cover_media_id) REFERENCES media (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE photo_galleries ADD CONSTRAINT FK_FAF03896B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE photo_gallery_items ADD CONSTRAINT FK_81B213B94E7AF8F FOREIGN KEY (gallery_id) REFERENCES photo_galleries (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE photo_gallery_items ADD CONSTRAINT FK_81B213B9EA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE photo_gallery_picks ADD CONSTRAINT FK_1CE6B23C2A151376 FOREIGN KEY (gallery_item_id) REFERENCES photo_gallery_items (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE photo_galleries DROP CONSTRAINT FK_FAF03896329A1B2E');
        $this->addSql('ALTER TABLE photo_galleries DROP CONSTRAINT FK_FAF03896B03A8386');
        $this->addSql('ALTER TABLE photo_gallery_items DROP CONSTRAINT FK_81B213B94E7AF8F');
        $this->addSql('ALTER TABLE photo_gallery_items DROP CONSTRAINT FK_81B213B9EA9FDD75');
        $this->addSql('ALTER TABLE photo_gallery_picks DROP CONSTRAINT FK_1CE6B23C2A151376');
        $this->addSql('DROP TABLE photo_galleries');
        $this->addSql('DROP TABLE photo_gallery_items');
        $this->addSql('DROP TABLE photo_gallery_picks');
    }
}
