<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260502182051 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ecommerce_orders ADD stripe_payment_intent_id VARCHAR(64) DEFAULT NULL');
        $this->addSql('ALTER TABLE ecommerce_orders ADD refunded_cents INT DEFAULT NULL');
        $this->addSql('ALTER TABLE photo_gallery_finalizations ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE photo_gallery_finalizations ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE photo_gallery_invites ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE photo_gallery_invites ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE photo_gallery_item_comments ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE photo_gallery_item_comments ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ecommerce_orders DROP stripe_payment_intent_id');
        $this->addSql('ALTER TABLE ecommerce_orders DROP refunded_cents');
        $this->addSql('ALTER TABLE photo_gallery_finalizations ALTER id SET DEFAULT nextval(\'photo_gallery_finalizations_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE photo_gallery_finalizations ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE photo_gallery_invites ALTER id SET DEFAULT nextval(\'photo_gallery_invites_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE photo_gallery_invites ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE photo_gallery_item_comments ALTER id SET DEFAULT nextval(\'photo_gallery_item_comments_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE photo_gallery_item_comments ALTER id DROP IDENTITY');
    }
}
