<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260424205144 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add media_folders table and focal/folder columns on media';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE media_folders (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, position INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_media_folders_parent ON media_folders (parent_id)');
        $this->addSql('ALTER TABLE media_folders ADD CONSTRAINT FK_9FE05546727ACA70 FOREIGN KEY (parent_id) REFERENCES media_folders (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media ADD focal_x DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE media ADD focal_y DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE media ADD folder_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT FK_6A2CA10C162CB942 FOREIGN KEY (folder_id) REFERENCES media_folders (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_6A2CA10C162CB942 ON media (folder_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE media_folders DROP CONSTRAINT FK_9FE05546727ACA70');
        $this->addSql('DROP TABLE media_folders');
        $this->addSql('ALTER TABLE media DROP CONSTRAINT FK_6A2CA10C162CB942');
        $this->addSql('DROP INDEX IDX_6A2CA10C162CB942');
        $this->addSql('ALTER TABLE media DROP focal_x');
        $this->addSql('ALTER TABLE media DROP focal_y');
        $this->addSql('ALTER TABLE media DROP folder_id');
    }
}
