<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260426155056 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ecommerce_order_lines (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title_snapshot VARCHAR(200) NOT NULL, sku_snapshot VARCHAR(64) NOT NULL, quantity INT NOT NULL, unit_price_cents INT NOT NULL, currency VARCHAR(3) NOT NULL, order_id INT NOT NULL, listing_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_95DE1CEC8D9F6D38 ON ecommerce_order_lines (order_id)');
        $this->addSql('CREATE INDEX IDX_95DE1CECD4619D1A ON ecommerce_order_lines (listing_id)');
        $this->addSql('CREATE TABLE ecommerce_orders (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number VARCHAR(32) NOT NULL, token VARCHAR(64) NOT NULL, status VARCHAR(16) DEFAULT \'pending\' NOT NULL, email VARCHAR(180) NOT NULL, name VARCHAR(200) NOT NULL, address_line1 VARCHAR(200) NOT NULL, address_line2 VARCHAR(200) DEFAULT NULL, city VARCHAR(100) NOT NULL, postal_code VARCHAR(20) NOT NULL, country VARCHAR(2) NOT NULL, notes TEXT DEFAULT NULL, total_cents INT NOT NULL, currency VARCHAR(3) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, customer_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_762161359395C3F3 ON ecommerce_orders (customer_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_ecommerce_order_number ON ecommerce_orders (number)');
        $this->addSql('CREATE UNIQUE INDEX uniq_ecommerce_order_token ON ecommerce_orders (token)');
        $this->addSql('ALTER TABLE ecommerce_order_lines ADD CONSTRAINT FK_95DE1CEC8D9F6D38 FOREIGN KEY (order_id) REFERENCES ecommerce_orders (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ecommerce_order_lines ADD CONSTRAINT FK_95DE1CECD4619D1A FOREIGN KEY (listing_id) REFERENCES ecommerce_listings (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ecommerce_orders ADD CONSTRAINT FK_762161359395C3F3 FOREIGN KEY (customer_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ecommerce_order_lines DROP CONSTRAINT FK_95DE1CEC8D9F6D38');
        $this->addSql('ALTER TABLE ecommerce_order_lines DROP CONSTRAINT FK_95DE1CECD4619D1A');
        $this->addSql('ALTER TABLE ecommerce_orders DROP CONSTRAINT FK_762161359395C3F3');
        $this->addSql('DROP TABLE ecommerce_order_lines');
        $this->addSql('DROP TABLE ecommerce_orders');
    }
}
