<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260503165706 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Rename billing_suppliers → billing_tiers with type discriminator, link invoice buyer to Tiers';
    }

    public function up(Schema $schema): void
    {
        // 1. Create billing_tiers with the same structure + type column
        $this->addSql('CREATE TABLE billing_tiers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, name VARCHAR(200) NOT NULL, vat_number VARCHAR(64) DEFAULT NULL, registration_number VARCHAR(64) DEFAULT NULL, iban VARCHAR(34) DEFAULT NULL, bic VARCHAR(11) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, address TEXT DEFAULT NULL, country_code VARCHAR(2) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, company_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_13381E8F979B1AD6 ON billing_tiers (company_id)');
        $this->addSql('ALTER TABLE billing_tiers ADD CONSTRAINT FK_13381E8F979B1AD6 FOREIGN KEY (company_id) REFERENCES crm_companies (id) ON DELETE SET NULL NOT DEFERRABLE');

        // 2. Migrate existing suppliers → tiers (keeping same IDs, type = supplier)
        $this->addSql("INSERT INTO billing_tiers (id, type, name, vat_number, registration_number, iban, bic, email, phone, address, country_code, created_at, updated_at, company_id) OVERRIDING SYSTEM VALUE SELECT id, 'supplier', name, vat_number, registration_number, iban, bic, email, phone, address, country_code, created_at, updated_at, company_id FROM billing_suppliers");
        // Sync the identity sequence so future inserts don't collide
        $this->addSql("SELECT setval(pg_get_serial_sequence('billing_tiers', 'id'), COALESCE((SELECT MAX(id) FROM billing_tiers), 0) + 1, false)");

        // 3. Update invoice FK: drop old constraint, rename column, add new FK
        $this->addSql('ALTER TABLE billing_invoices DROP CONSTRAINT fk_72f346692add6d8c');
        $this->addSql('DROP INDEX idx_72f346692add6d8c');
        $this->addSql('ALTER TABLE billing_invoices RENAME COLUMN supplier_id TO tiers_id');
        $this->addSql('ALTER TABLE billing_invoices ADD buyer_tiers_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE billing_invoices DROP buyer_name');
        $this->addSql('ALTER TABLE billing_invoices DROP buyer_vat_number');
        $this->addSql('ALTER TABLE billing_invoices DROP buyer_address');
        $this->addSql('ALTER TABLE billing_invoices DROP buyer_country_code');
        $this->addSql('ALTER TABLE billing_invoices DROP buyer_email');
        $this->addSql('ALTER TABLE billing_invoices DROP buyer_phone');
        $this->addSql('ALTER TABLE billing_invoices ADD CONSTRAINT FK_72F3466968B77723 FOREIGN KEY (tiers_id) REFERENCES billing_tiers (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE billing_invoices ADD CONSTRAINT FK_72F34669D1710F83 FOREIGN KEY (buyer_tiers_id) REFERENCES billing_tiers (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_72F3466968B77723 ON billing_invoices (tiers_id)');
        $this->addSql('CREATE INDEX IDX_72F34669D1710F83 ON billing_invoices (buyer_tiers_id)');

        // 4. Drop old suppliers table
        $this->addSql('DROP TABLE billing_suppliers');
    }

    public function down(Schema $schema): void
    {
        // Recreate billing_suppliers from supplier-type rows in billing_tiers
        $this->addSql('CREATE TABLE billing_suppliers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, vat_number VARCHAR(64) DEFAULT NULL, registration_number VARCHAR(64) DEFAULT NULL, iban VARCHAR(34) DEFAULT NULL, bic VARCHAR(11) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, address TEXT DEFAULT NULL, country_code VARCHAR(2) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, company_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql("INSERT INTO billing_suppliers (id, name, vat_number, registration_number, iban, bic, email, phone, address, country_code, created_at, updated_at, company_id) OVERRIDING SYSTEM VALUE SELECT id, name, vat_number, registration_number, iban, bic, email, phone, address, country_code, created_at, updated_at, company_id FROM billing_tiers WHERE type = 'supplier'");
        $this->addSql('ALTER TABLE billing_tiers DROP CONSTRAINT FK_13381E8F979B1AD6');
        $this->addSql('DROP TABLE billing_tiers');
        $this->addSql('ALTER TABLE billing_invoices DROP CONSTRAINT FK_72F3466968B77723');
        $this->addSql('ALTER TABLE billing_invoices DROP CONSTRAINT FK_72F34669D1710F83');
        $this->addSql('DROP INDEX IDX_72F3466968B77723');
        $this->addSql('DROP INDEX IDX_72F34669D1710F83');
        $this->addSql('ALTER TABLE billing_invoices ADD supplier_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE billing_invoices ADD buyer_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE billing_invoices ADD buyer_vat_number VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE billing_invoices ADD buyer_address TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE billing_invoices ADD buyer_country_code VARCHAR(2) DEFAULT NULL');
        $this->addSql('ALTER TABLE billing_invoices ADD buyer_email VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE billing_invoices ADD buyer_phone VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE billing_invoices DROP tiers_id');
        $this->addSql('ALTER TABLE billing_invoices DROP buyer_tiers_id');
        $this->addSql('ALTER TABLE billing_invoices ADD CONSTRAINT fk_72f346692add6d8c FOREIGN KEY (supplier_id) REFERENCES billing_suppliers (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_72f346692add6d8c ON billing_invoices (supplier_id)');
    }
}
