<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260426154753 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create ecommerce_carts and ecommerce_cart_items tables (Ecommerce module — Cart/CartItem entities).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE ecommerce_cart_items (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, unit_price_cents INT NOT NULL, currency VARCHAR(3) NOT NULL, cart_id INT NOT NULL, listing_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4C2D14391AD5CDBF ON ecommerce_cart_items (cart_id)');
        $this->addSql('CREATE INDEX IDX_4C2D1439D4619D1A ON ecommerce_cart_items (listing_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_ecommerce_cart_item_listing ON ecommerce_cart_items (cart_id, listing_id)');
        $this->addSql('CREATE TABLE ecommerce_carts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, session_id VARCHAR(64) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_ecommerce_cart_session ON ecommerce_carts (session_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_ecommerce_cart_user ON ecommerce_carts (user_id)');
        $this->addSql('ALTER TABLE ecommerce_cart_items ADD CONSTRAINT FK_4C2D14391AD5CDBF FOREIGN KEY (cart_id) REFERENCES ecommerce_carts (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ecommerce_cart_items ADD CONSTRAINT FK_4C2D1439D4619D1A FOREIGN KEY (listing_id) REFERENCES ecommerce_listings (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ecommerce_carts ADD CONSTRAINT FK_49630C21A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE ecommerce_cart_items DROP CONSTRAINT FK_4C2D14391AD5CDBF');
        $this->addSql('ALTER TABLE ecommerce_cart_items DROP CONSTRAINT FK_4C2D1439D4619D1A');
        $this->addSql('ALTER TABLE ecommerce_carts DROP CONSTRAINT FK_49630C21A76ED395');
        $this->addSql('DROP TABLE ecommerce_cart_items');
        $this->addSql('DROP TABLE ecommerce_carts');
    }
}
