<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Refonte du module Menu :
 *  - menu_items : remplace label/url/locale par target_type/target_id/custom_url + visibility/css_class + timestamps
 *  - nouvelle table menu_item_translations (label override par locale)
 *  - menus : description + timestamps
 */
final class Version20260425163328 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Refonte module Menu: smart targets + translations + timestamps';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE menu_item_translations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(10) NOT NULL, label VARCHAR(255) DEFAULT NULL, menu_item_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_24D3F7359AB44FE0 ON menu_item_translations (menu_item_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_menu_item_locale ON menu_item_translations (menu_item_id, locale)');
        $this->addSql('ALTER TABLE menu_item_translations ADD CONSTRAINT FK_24D3F7359AB44FE0 FOREIGN KEY (menu_item_id) REFERENCES menu_items (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('ALTER TABLE menu_items DROP CONSTRAINT fk_70b2ca2a727aca70');
        $this->addSql("ALTER TABLE menu_items ADD target_type VARCHAR(30) NOT NULL DEFAULT 'custom_url'");
        $this->addSql('ALTER TABLE menu_items ADD target_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE menu_items ADD custom_url VARCHAR(1000) DEFAULT NULL');
        $this->addSql('ALTER TABLE menu_items ADD css_class VARCHAR(255) DEFAULT NULL');
        $this->addSql("ALTER TABLE menu_items ADD visibility VARCHAR(30) NOT NULL DEFAULT 'always'");
        $this->addSql('ALTER TABLE menu_items ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE menu_items ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE menu_items ALTER target_type DROP DEFAULT');
        $this->addSql('ALTER TABLE menu_items ALTER visibility DROP DEFAULT');
        $this->addSql('ALTER TABLE menu_items ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE menu_items ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE menu_items DROP locale');
        $this->addSql('ALTER TABLE menu_items DROP label');
        $this->addSql('ALTER TABLE menu_items DROP url');
        $this->addSql('ALTER TABLE menu_items ADD CONSTRAINT FK_70B2CA2A727ACA70 FOREIGN KEY (parent_id) REFERENCES menu_items (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('ALTER TABLE menus ADD description VARCHAR(500) DEFAULT NULL');
        $this->addSql('ALTER TABLE menus ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE menus ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE menus ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE menus ALTER updated_at DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE menu_item_translations DROP CONSTRAINT FK_24D3F7359AB44FE0');
        $this->addSql('DROP TABLE menu_item_translations');
        $this->addSql('ALTER TABLE menu_items DROP CONSTRAINT FK_70B2CA2A727ACA70');
        $this->addSql("ALTER TABLE menu_items ADD locale VARCHAR(10) NOT NULL DEFAULT 'fr'");
        $this->addSql("ALTER TABLE menu_items ADD label VARCHAR(255) NOT NULL DEFAULT ''");
        $this->addSql("ALTER TABLE menu_items ADD url VARCHAR(500) NOT NULL DEFAULT ''");
        $this->addSql('ALTER TABLE menu_items ALTER locale DROP DEFAULT');
        $this->addSql('ALTER TABLE menu_items ALTER label DROP DEFAULT');
        $this->addSql('ALTER TABLE menu_items ALTER url DROP DEFAULT');
        $this->addSql('ALTER TABLE menu_items DROP target_type');
        $this->addSql('ALTER TABLE menu_items DROP target_id');
        $this->addSql('ALTER TABLE menu_items DROP custom_url');
        $this->addSql('ALTER TABLE menu_items DROP css_class');
        $this->addSql('ALTER TABLE menu_items DROP visibility');
        $this->addSql('ALTER TABLE menu_items DROP created_at');
        $this->addSql('ALTER TABLE menu_items DROP updated_at');
        $this->addSql('ALTER TABLE menu_items ADD CONSTRAINT fk_70b2ca2a727aca70 FOREIGN KEY (parent_id) REFERENCES menu_items (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE menus DROP description');
        $this->addSql('ALTER TABLE menus DROP created_at');
        $this->addSql('ALTER TABLE menus DROP updated_at');
    }
}
