<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Introduce hierarchical taxonomies and migrate the legacy flat tags
 * into a dedicated non-hierarchical "tag" taxonomy.
 */
final class Version20260424192037 extends AbstractMigration
{
    private const LOCALES = ['fr', 'en', 'es', 'de'];

    private const TAXONOMY_LABELS = [
        'tag' => ['fr' => 'Étiquette', 'en' => 'Tag', 'es' => 'Etiqueta', 'de' => 'Schlagwort'],
        'category' => ['fr' => 'Catégorie', 'en' => 'Category', 'es' => 'Categoría', 'de' => 'Kategorie'],
    ];

    public function getDescription(): string
    {
        return 'Introduce Taxonomy/TaxonomyTerm system with i18n, migrate legacy tags, drop tags table';
    }

    public function up(Schema $schema): void
    {
        // ── 1. Create new taxonomy tables ───────────────────────────────────
        $this->addSql('CREATE TABLE post_type_taxonomies (post_type_id INT NOT NULL, taxonomy_id INT NOT NULL, PRIMARY KEY (post_type_id, taxonomy_id))');
        $this->addSql('CREATE INDEX IDX_731E96B4F8A43BA0 ON post_type_taxonomies (post_type_id)');
        $this->addSql('CREATE INDEX IDX_731E96B49557E6F6 ON post_type_taxonomies (taxonomy_id)');
        $this->addSql('CREATE TABLE post_terms (post_id INT NOT NULL, taxonomy_term_id INT NOT NULL, PRIMARY KEY (post_id, taxonomy_term_id))');
        $this->addSql('CREATE INDEX IDX_1FB9B39E4B89032C ON post_terms (post_id)');
        $this->addSql('CREATE INDEX IDX_1FB9B39E898CA496 ON post_terms (taxonomy_term_id)');
        $this->addSql('CREATE TABLE taxonomies (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(100) NOT NULL, hierarchical BOOLEAN NOT NULL, is_built_in BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_232B80F9989D9B62 ON taxonomies (slug)');
        $this->addSql('CREATE TABLE taxonomy_term_translations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(10) NOT NULL, name VARCHAR(150) NOT NULL, slug VARCHAR(180) NOT NULL, description TEXT DEFAULT NULL, term_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_67F9D347E2C35FC ON taxonomy_term_translations (term_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_67F9D347E2C35FC4180C698 ON taxonomy_term_translations (term_id, locale)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_term_locale_slug ON taxonomy_term_translations (locale, slug)');
        $this->addSql('CREATE TABLE taxonomy_terms (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, taxonomy_id INT NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DDC5FBDC9557E6F6 ON taxonomy_terms (taxonomy_id)');
        $this->addSql('CREATE INDEX IDX_DDC5FBDC727ACA70 ON taxonomy_terms (parent_id)');
        $this->addSql('CREATE INDEX IDX_taxonomy_term_taxonomy_parent ON taxonomy_terms (taxonomy_id, parent_id)');
        $this->addSql('CREATE TABLE taxonomy_translations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(10) NOT NULL, label VARCHAR(150) NOT NULL, description VARCHAR(255) DEFAULT NULL, taxonomy_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BD7360469557E6F6 ON taxonomy_translations (taxonomy_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BD7360469557E6F64180C698 ON taxonomy_translations (taxonomy_id, locale)');
        $this->addSql('ALTER TABLE post_type_taxonomies ADD CONSTRAINT FK_731E96B4F8A43BA0 FOREIGN KEY (post_type_id) REFERENCES post_types (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_type_taxonomies ADD CONSTRAINT FK_731E96B49557E6F6 FOREIGN KEY (taxonomy_id) REFERENCES taxonomies (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_terms ADD CONSTRAINT FK_1FB9B39E4B89032C FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_terms ADD CONSTRAINT FK_1FB9B39E898CA496 FOREIGN KEY (taxonomy_term_id) REFERENCES taxonomy_terms (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE taxonomy_term_translations ADD CONSTRAINT FK_67F9D347E2C35FC FOREIGN KEY (term_id) REFERENCES taxonomy_terms (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE taxonomy_terms ADD CONSTRAINT FK_DDC5FBDC9557E6F6 FOREIGN KEY (taxonomy_id) REFERENCES taxonomies (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE taxonomy_terms ADD CONSTRAINT FK_DDC5FBDC727ACA70 FOREIGN KEY (parent_id) REFERENCES taxonomy_terms (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE taxonomy_translations ADD CONSTRAINT FK_BD7360469557E6F6 FOREIGN KEY (taxonomy_id) REFERENCES taxonomies (id) ON DELETE CASCADE NOT DEFERRABLE');

        // ── 2. Seed built-in taxonomies ─────────────────────────────────────
        $now = 'CURRENT_TIMESTAMP';
        foreach (self::TAXONOMY_LABELS as $slug => $labels) {
            $hierarchical = 'category' === $slug ? 'true' : 'false';
            $this->addSql(sprintf(
                "INSERT INTO taxonomies (slug, hierarchical, is_built_in, created_at, updated_at) VALUES ('%s', %s, true, %s, %s)",
                $slug,
                $hierarchical,
                $now,
                $now,
            ));
            foreach (self::LOCALES as $locale) {
                $label = $labels[$locale] ?? $labels['en'];
                $this->addSql(sprintf(
                    "INSERT INTO taxonomy_translations (taxonomy_id, locale, label) VALUES ((SELECT id FROM taxonomies WHERE slug = '%s'), '%s', '%s')",
                    $slug,
                    $locale,
                    addslashes($label),
                ));
            }
        }

        // ── 3. Attach both taxonomies to every existing post type ───────────
        $this->addSql("INSERT INTO post_type_taxonomies (post_type_id, taxonomy_id) SELECT pt.id, t.id FROM post_types pt CROSS JOIN taxonomies t WHERE t.slug IN ('tag', 'category')");

        // ── 4. Migrate existing tags → terms under the 'tag' taxonomy ──────
        // For each Tag row, create a TaxonomyTerm and a translation in every
        // enabled locale using the same name/slug (admins will localise later).
        $this->addSql("INSERT INTO taxonomy_terms (taxonomy_id, position, created_at, updated_at) SELECT (SELECT id FROM taxonomies WHERE slug = 'tag'), t.id, t.created_at, t.updated_at FROM tags t ORDER BY t.id");

        // Because each Tag maps to exactly one new term, we correlate via
        // the position=id convention we used above.
        foreach (self::LOCALES as $locale) {
            $this->addSql(sprintf(
                "INSERT INTO taxonomy_term_translations (term_id, locale, name, slug) SELECT tt.id, '%s', t.name, t.slug FROM taxonomy_terms tt JOIN tags t ON t.id = tt.position WHERE tt.taxonomy_id = (SELECT id FROM taxonomies WHERE slug = 'tag')",
                $locale,
            ));
        }

        // ── 5. Migrate tag_post junction → post_terms ───────────────────────
        $this->addSql("INSERT INTO post_terms (post_id, taxonomy_term_id) SELECT tp.post_id, tt.id FROM tag_post tp JOIN taxonomy_terms tt ON tt.position = tp.tag_id AND tt.taxonomy_id = (SELECT id FROM taxonomies WHERE slug = 'tag')");

        // ── 6. Reset positions (we used position as a tmp correlation key) ──
        $this->addSql("UPDATE taxonomy_terms SET position = 0 WHERE taxonomy_id = (SELECT id FROM taxonomies WHERE slug = 'tag')");

        // ── 7. Drop legacy tag tables ───────────────────────────────────────
        $this->addSql('DROP TABLE IF EXISTS tag_post');
        $this->addSql('DROP TABLE IF EXISTS tags');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE post_type_taxonomies DROP CONSTRAINT FK_731E96B4F8A43BA0');
        $this->addSql('ALTER TABLE post_type_taxonomies DROP CONSTRAINT FK_731E96B49557E6F6');
        $this->addSql('ALTER TABLE post_terms DROP CONSTRAINT FK_1FB9B39E4B89032C');
        $this->addSql('ALTER TABLE post_terms DROP CONSTRAINT FK_1FB9B39E898CA496');
        $this->addSql('ALTER TABLE taxonomy_term_translations DROP CONSTRAINT FK_67F9D347E2C35FC');
        $this->addSql('ALTER TABLE taxonomy_terms DROP CONSTRAINT FK_DDC5FBDC9557E6F6');
        $this->addSql('ALTER TABLE taxonomy_terms DROP CONSTRAINT FK_DDC5FBDC727ACA70');
        $this->addSql('ALTER TABLE taxonomy_translations DROP CONSTRAINT FK_BD7360469557E6F6');
        $this->addSql('DROP TABLE post_type_taxonomies');
        $this->addSql('DROP TABLE post_terms');
        $this->addSql('DROP TABLE taxonomies');
        $this->addSql('DROP TABLE taxonomy_term_translations');
        $this->addSql('DROP TABLE taxonomy_terms');
        $this->addSql('DROP TABLE taxonomy_translations');
        // Legacy `tags` / `posts_tags` recreation intentionally omitted (data loss is acceptable on rollback).
    }
}
