<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260424190509 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add SEO fields on post_translations and post_slug_history table';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE post_slug_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(10) NOT NULL, slug VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, post_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_post_slug_history_post ON post_slug_history (post_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_post_slug_history_locale_slug ON post_slug_history (locale, slug)');
        $this->addSql('ALTER TABLE post_slug_history ADD CONSTRAINT FK_C74000A94B89032C FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post_translations ADD canonical_url VARCHAR(500) DEFAULT NULL');
        $this->addSql('ALTER TABLE post_translations ADD noindex BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE post_translations ADD focus_keyword VARCHAR(120) DEFAULT NULL');
        $this->addSql('ALTER TABLE post_translations ADD json_ld JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE post_translations ADD og_image_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE post_translations ADD CONSTRAINT FK_6D8AA7546EFCB8B8 FOREIGN KEY (og_image_id) REFERENCES media (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_6D8AA7546EFCB8B8 ON post_translations (og_image_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE post_slug_history DROP CONSTRAINT FK_C74000A94B89032C');
        $this->addSql('DROP TABLE post_slug_history');
        $this->addSql('ALTER TABLE post_translations DROP CONSTRAINT FK_6D8AA7546EFCB8B8');
        $this->addSql('DROP INDEX IDX_6D8AA7546EFCB8B8');
        $this->addSql('ALTER TABLE post_translations DROP canonical_url');
        $this->addSql('ALTER TABLE post_translations DROP noindex');
        $this->addSql('ALTER TABLE post_translations DROP focus_keyword');
        $this->addSql('ALTER TABLE post_translations DROP json_ld');
        $this->addSql('ALTER TABLE post_translations DROP og_image_id');
    }
}
