<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260426124234 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create erp_products table (Erp module — Product entity).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE erp_products (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, sku VARCHAR(64) NOT NULL, description TEXT DEFAULT NULL, price_cents INT DEFAULT NULL, currency VARCHAR(3) DEFAULT \'EUR\' NOT NULL, status VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_erp_product_sku ON erp_products (sku)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE erp_products');
    }
}
