<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260425130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Make Form module multilingual: add form_translations and form_field_translations, drop translatable columns from forms and form_fields, add locale to form_submissions';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE form_fields DROP CONSTRAINT FK_6E5706165FF69B7D');
        $this->addSql('ALTER TABLE form_submissions DROP CONSTRAINT FK_8540AF9F5FF69B7D');
        $this->addSql('DROP TABLE form_submissions');
        $this->addSql('DROP TABLE form_fields');
        $this->addSql('DROP TABLE forms');

        $this->addSql('CREATE TABLE forms (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, notify_email VARCHAR(180) DEFAULT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN forms.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN forms.updated_at IS \'(DC2Type:datetime_immutable)\'');

        $this->addSql('CREATE TABLE form_translations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, form_id INT NOT NULL, locale VARCHAR(10) NOT NULL, title VARCHAR(200) NOT NULL, slug VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FORM_TRANS_FORM ON form_translations (form_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_form_translation_locale ON form_translations (form_id, locale)');
        $this->addSql('CREATE UNIQUE INDEX uniq_form_translation_slug ON form_translations (locale, slug)');
        $this->addSql('ALTER TABLE form_translations ADD CONSTRAINT FK_FORM_TRANS_FORM FOREIGN KEY (form_id) REFERENCES forms (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE form_fields (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, form_id INT NOT NULL, type VARCHAR(50) NOT NULL, required BOOLEAN NOT NULL, position INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6E5706165FF69B7D ON form_fields (form_id)');
        $this->addSql('ALTER TABLE form_fields ADD CONSTRAINT FK_6E5706165FF69B7D FOREIGN KEY (form_id) REFERENCES forms (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE form_field_translations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, field_id INT NOT NULL, locale VARCHAR(10) NOT NULL, label VARCHAR(200) NOT NULL, placeholder VARCHAR(200) DEFAULT NULL, options JSON NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FFT_FIELD ON form_field_translations (field_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_field_translation_locale ON form_field_translations (field_id, locale)');
        $this->addSql('ALTER TABLE form_field_translations ADD CONSTRAINT FK_FFT_FIELD FOREIGN KEY (field_id) REFERENCES form_fields (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE form_submissions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, form_id INT NOT NULL, data JSON NOT NULL, locale VARCHAR(10) NOT NULL, submitted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ip VARCHAR(45) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8540AF9F5FF69B7D ON form_submissions (form_id)');
        $this->addSql('COMMENT ON COLUMN form_submissions.submitted_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE form_submissions ADD CONSTRAINT FK_8540AF9F5FF69B7D FOREIGN KEY (form_id) REFERENCES forms (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE form_translations DROP CONSTRAINT FK_FORM_TRANS_FORM');
        $this->addSql('ALTER TABLE form_field_translations DROP CONSTRAINT FK_FFT_FIELD');
        $this->addSql('ALTER TABLE form_fields DROP CONSTRAINT FK_6E5706165FF69B7D');
        $this->addSql('ALTER TABLE form_submissions DROP CONSTRAINT FK_8540AF9F5FF69B7D');
        $this->addSql('DROP TABLE form_submissions');
        $this->addSql('DROP TABLE form_field_translations');
        $this->addSql('DROP TABLE form_fields');
        $this->addSql('DROP TABLE form_translations');
        $this->addSql('DROP TABLE forms');
    }
}
