<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260426101339 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE audit_logs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, module VARCHAR(30) NOT NULL, action VARCHAR(100) NOT NULL, entity_type VARCHAR(100) DEFAULT NULL, entity_id INT DEFAULT NULL, user_id INT DEFAULT NULL, user_email VARCHAR(180) DEFAULT NULL, data JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE crm_companies (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, industry VARCHAR(100) DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE crm_deals (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, stage VARCHAR(20) DEFAULT \'lead\' NOT NULL, value NUMERIC(12, 2) DEFAULT NULL, closing_date DATE DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, contact_id INT DEFAULT NULL, company_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5330DBA3E7A1254A ON crm_deals (contact_id)');
        $this->addSql('CREATE INDEX IDX_5330DBA3979B1AD6 ON crm_deals (company_id)');
        $this->addSql('ALTER TABLE crm_deals ADD CONSTRAINT FK_5330DBA3E7A1254A FOREIGN KEY (contact_id) REFERENCES crm_contacts (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE crm_deals ADD CONSTRAINT FK_5330DBA3979B1AD6 FOREIGN KEY (company_id) REFERENCES crm_companies (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE crm_deals DROP CONSTRAINT FK_5330DBA3E7A1254A');
        $this->addSql('ALTER TABLE crm_deals DROP CONSTRAINT FK_5330DBA3979B1AD6');
        $this->addSql('DROP TABLE audit_logs');
        $this->addSql('DROP TABLE crm_companies');
        $this->addSql('DROP TABLE crm_deals');
    }
}
