<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260425120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add forms, form_fields and form_submissions tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE forms (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(200) NOT NULL, slug VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, notify_email VARCHAR(180) DEFAULT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FE602273989D9B62 ON forms (slug)');
        $this->addSql('COMMENT ON COLUMN forms.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN forms.updated_at IS \'(DC2Type:datetime_immutable)\'');

        $this->addSql('CREATE TABLE form_fields (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, form_id INT NOT NULL, type VARCHAR(50) NOT NULL, label VARCHAR(200) NOT NULL, placeholder VARCHAR(200) DEFAULT NULL, required BOOLEAN NOT NULL, options JSON NOT NULL, position INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6E5706165FF69B7D ON form_fields (form_id)');
        $this->addSql('ALTER TABLE form_fields ADD CONSTRAINT FK_6E5706165FF69B7D FOREIGN KEY (form_id) REFERENCES forms (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE form_submissions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, form_id INT NOT NULL, data JSON NOT NULL, submitted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ip VARCHAR(45) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8540AF9F5FF69B7D ON form_submissions (form_id)');
        $this->addSql('COMMENT ON COLUMN form_submissions.submitted_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE form_submissions ADD CONSTRAINT FK_8540AF9F5FF69B7D FOREIGN KEY (form_id) REFERENCES forms (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE form_fields DROP CONSTRAINT FK_6E5706165FF69B7D');
        $this->addSql('ALTER TABLE form_submissions DROP CONSTRAINT FK_8540AF9F5FF69B7D');
        $this->addSql('DROP TABLE form_submissions');
        $this->addSql('DROP TABLE form_fields');
        $this->addSql('DROP TABLE forms');
    }
}
