<?php

declare(strict_types=1);

namespace {{NAMESPACE}}\Setting;

use Aurora\Module\Configuration\Setting\Enum\ApplicationParameterEnumInterface;

/**
 * Module-specific settings for {{MODULE_LABEL}}. Edit this enum to declare
 * your own configurable parameters. Each case becomes a row in
 * `core_settings` (synchronised by `bin/console aurora:application-parameter`)
 * and a field in the admin Settings tab generated by
 * {@see {{MODULE}}ConfigurationTabProvider}.
 */
enum {{MODULE}}SettingEnum: string implements ApplicationParameterEnumInterface
{
    // Example case — replace with your own.
    case ExampleFlag = '{{MODULE_ID}}_example_flag';

    public function getKey(): string
    {
        return $this->value;
    }

    public function getType(): string
    {
        return match ($this) {
            self::ExampleFlag => 'boolean',
        };
    }

    public function getDefaultValue(): string
    {
        return match ($this) {
            self::ExampleFlag => '0',
        };
    }

    public function getLabel(): string
    {
        return match ($this) {
            self::ExampleFlag => 'backend.{{MODULE_ID}}.settings.example_flag',
        };
    }

    public function getDescription(): string
    {
        return match ($this) {
            self::ExampleFlag => 'backend.{{MODULE_ID}}.settings.example_flag_description',
        };
    }

    public function getGroup(): string
    {
        return '{{MODULE_ID}}';
    }
}
